package com.sengine.engine.core

import com.sengine.engine.script.NativeScripts
import kotlin.math.abs
import kotlin.math.floor
import kotlin.math.max
import kotlin.math.min
import kotlin.math.sqrt

/**
 * Landscape: large procedural terrain generated by the native C++ engine (fBm + ridged noise, island falloff,
 * terraces and droplet hydraulic erosion). Rendered as a lit mesh with an auto-painted colour map
 * (sand / grass / rock / snow by height and slope), collides with Rigidbody3D bodies and is hit by ray casts.
 *
 * The terrain is centred on the object; only the object's position is used (rotation / scale are ignored).
 */
class Landscape : Component() {
    override val type = "Landscape"
    var resolution = 97
    var size = 120f
    var height = 18f
    var seed = 7
    var octaves = 6
    var frequency = 2.5f
    var persistence = 0.5f
    var ridge = 0.35f
    var falloff = 0f
    var terraces = 0f
    var erosion = 15000
    var waterLevel = 0.18f
    var paint = true
    var sandColor = 0xFFD8C690.toInt()
    var grassColor = 0xFF5E9A45.toInt()
    var rockColor = 0xFF7D756B.toInt()
    var snowColor = 0xFFF2F4F7.toInt()
    var texture = ""
    var tiling = 1f

    // ---------------------------------------------------------------- runtime
    @Transient var heights: FloatArray? = null
    @Transient var mesh: FloatArray? = null
    /** Bumped every time the terrain is regenerated (renderer re-uploads its mesh/texture). */
    @Transient var version = 0
    @Transient var generatedNatively = false
    @Transient private var key = ""

    override fun props() = listOf(
        Prop.I("Resolution", { resolution }, { resolution = it.coerceIn(9, 257) }),
        Prop.F("Size", { size }, { size = it.coerceIn(4f, 2000f) }),
        Prop.F("Height", { height }, { height = it.coerceIn(0f, 500f) }),
        Prop.I("Seed", { seed }, { seed = it }),
        Prop.I("Octaves", { octaves }, { octaves = it.coerceIn(1, 10) }),
        Prop.F("Frequency", { frequency }, { frequency = it.coerceIn(0.1f, 40f) }),
        Prop.F("Roughness", { persistence }, { persistence = it.coerceIn(0.05f, 0.95f) }, 0.05f),
        Prop.F("Ridges", { ridge }, { ridge = it.coerceIn(0f, 1f) }, 0.05f),
        Prop.F("Island Falloff", { falloff }, { falloff = it.coerceIn(0f, 1f) }, 0.05f),
        Prop.F("Terraces", { terraces }, { terraces = it.coerceIn(0f, 32f) }, 1f),
        Prop.I("Erosion Drops", { erosion }, { erosion = it.coerceIn(0, 300000) }),
        Prop.F("Beach Level", { waterLevel }, { waterLevel = it.coerceIn(0f, 0.9f) }, 0.02f),
        Prop.B("Auto Paint", { paint }, { paint = it }),
        Prop.Color("Sand", { sandColor }, { sandColor = it }),
        Prop.Color("Grass", { grassColor }, { grassColor = it }),
        Prop.Color("Rock", { rockColor }, { rockColor = it }),
        Prop.Color("Snow", { snowColor }, { snowColor = it }),
        Prop.Asset("Texture", AssetKind.TEXTURE, { texture }, { texture = it }),
        Prop.F("Tiling", { tiling }, { tiling = it.coerceIn(0.01f, 200f) }),
    )

    private fun paramsKey() = "$resolution|$size|$height|$seed|$octaves|$frequency|$persistence|$ridge|$falloff|$terraces|$erosion|$waterLevel"
    private fun ints() = intArrayOf(resolution, seed, octaves, erosion)
    private fun floats() = floatArrayOf(size, height, frequency, persistence, 2f, ridge, falloff, terraces, waterLevel)

    /** Generates (or re-generates after a property change) the height field and mesh. Cheap when nothing changed. */
    fun ensure(): FloatArray {
        val k = paramsKey()
        heights?.let { if (k == key) return it }
        key = k
        val n = resolution
        val h = if (NativeScripts.available) try {
            NativeScripts.nTerrainHeights(ints(), floats()).also { generatedNatively = true }
        } catch (_: Throwable) { null } else null
        val result = h ?: fallbackHeights().also { generatedNatively = false }
        heights = result
        mesh = buildMesh(result, n)
        version++
        return result
    }

    /** Height (world units, relative to the object) at local (x, z); 0 outside the terrain. */
    fun heightAt(x: Float, z: Float): Float {
        val h = heights?.takeIf { it.size == resolution * resolution } ?: ensure()
        val n = resolution
        val gx = ((x / size + 0.5f) * (n - 1)).coerceIn(0f, n - 1 - 1e-4f)
        val gz = ((z / size + 0.5f) * (n - 1)).coerceIn(0f, n - 1 - 1e-4f)
        val ix = gx.toInt(); val iz = gz.toInt()
        val u = gx - ix; val v = gz - iz
        val ix1 = min(n - 1, ix + 1); val iz1 = min(n - 1, iz + 1)
        val a = h[iz * n + ix]; val b = h[iz * n + ix1]; val c = h[iz1 * n + ix]; val d = h[iz1 * n + ix1]
        return (a * (1 - u) + b * u) * (1 - v) + (c * (1 - u) + d * u) * v
    }

    fun contains(x: Float, z: Float) = abs(x) <= size / 2 && abs(z) <= size / 2

    /** Surface normal at local (x, z). */
    fun normalAt(x: Float, z: Float): FloatArray {
        val e = size / (resolution - 1)
        val nx = heightAt(x - e, z) - heightAt(x + e, z)
        val nz = heightAt(x, z - e) - heightAt(x, z + e)
        val ny = 2 * e
        val l = sqrt(nx * nx + ny * ny + nz * nz)
        return floatArrayOf(nx / l, ny / l, nz / l)
    }

    /** ARGB colour map (res × res) painted by height and slope, used as the terrain texture. */
    fun colorMap(res: Int): IntArray {
        ensure()
        val out = IntArray(res * res)
        val step = size / (res - 1)
        for (j in 0 until res) for (i in 0 until res) {
            val x = -size / 2 + i * step; val z = -size / 2 + j * step
            val h = heightAt(x, z) / max(0.001f, height)
            val slope = 1f - normalAt(x, z)[1]
            var c = when {
                h < waterLevel + 0.03f -> sandColor
                h < 0.62f -> lerp(grassColor, darken(grassColor, 0.75f), ((h - waterLevel) / 0.6f).coerceIn(0f, 1f))
                h < 0.8f -> lerp(grassColor, rockColor, (h - 0.62f) / 0.18f)
                else -> lerp(rockColor, snowColor, ((h - 0.8f) / 0.08f).coerceIn(0f, 1f))
            }
            if (slope > 0.18f) c = lerp(c, rockColor, ((slope - 0.18f) * 4f).coerceIn(0f, 1f))
            // subtle per-texel variation so large areas don't look flat
            val n = ((i * 73856093) xor (j * 19349663)) and 0xFF
            out[j * res + i] = darken(c, 0.93f + n / 255f * 0.07f)
        }
        return out
    }

    private fun buildMesh(h: FloatArray, n: Int): FloatArray {
        val nat = if (NativeScripts.available) try { NativeScripts.nTerrainMesh(ints(), floats(), h) } catch (_: Throwable) { null } else null
        val grid = nat ?: FloatArray(n * n * 8).also { g ->
            val step = size / (n - 1)
            for (z in 0 until n) for (x in 0 until n) {
                val i = z * n + x
                val hl = h[z * n + max(0, x - 1)]; val hr = h[z * n + min(n - 1, x + 1)]
                val hd = h[max(0, z - 1) * n + x]; val hu = h[min(n - 1, z + 1) * n + x]
                val nx = hl - hr; val nz = hd - hu; val ny = 2 * step
                val l = sqrt(nx * nx + ny * ny + nz * nz)
                g[i * 8] = -size / 2 + x * step; g[i * 8 + 1] = h[i]; g[i * 8 + 2] = -size / 2 + z * step
                g[i * 8 + 3] = nx / l; g[i * 8 + 4] = ny / l; g[i * 8 + 5] = nz / l
                g[i * 8 + 6] = x / (n - 1f); g[i * 8 + 7] = z / (n - 1f)
            }
        }
        // expand the indexed grid into the renderer's non-indexed triangle list
        val out = FloatArray((n - 1) * (n - 1) * 6 * 8)
        var o = 0
        fun put(v: Int) { System.arraycopy(grid, v * 8, out, o, 8); o += 8 }
        for (z in 0 until n - 1) for (x in 0 until n - 1) {
            val a = z * n + x; val b = a + 1; val c = a + n; val d = c + 1
            put(a); put(c); put(b); put(b); put(c); put(d)
        }
        return out
    }

    /** Pure-Kotlin fallback (no erosion) used only when the native library can't be loaded. */
    private fun fallbackHeights(): FloatArray {
        val n = resolution
        val out = FloatArray(n * n)
        var lo = Float.MAX_VALUE; var hi = -Float.MAX_VALUE
        for (y in 0 until n) for (x in 0 until n) {
            var amp = 1f; var freq = frequency; var sum = 0f; var norm = 0f
            for (o in 0 until octaves) {
                val v = valueNoise(x / (n - 1f) * freq + o * 17.3f, y / (n - 1f) * freq - o * 9.1f, seed + o * 131)
                val r = 1 - abs(v); sum += amp * (v * (1 - ridge) + (r * r * 2 - 1) * ridge); norm += amp
                amp *= persistence; freq *= 2f
            }
            val v = sum / norm
            out[y * n + x] = v; lo = min(lo, v); hi = max(hi, v)
        }
        for (i in out.indices) out[i] = ((out[i] - lo) / max(1e-6f, hi - lo)) * height
        return out
    }

    private fun valueNoise(x: Float, y: Float, s: Int): Float {
        val x0 = floor(x).toInt(); val y0 = floor(y).toInt()
        val fx = x - x0; val fy = y - y0
        val u = fx * fx * (3 - 2 * fx); val v = fy * fy * (3 - 2 * fy)
        fun r(ix: Int, iy: Int): Float { var h = ix * 374761393 + iy * 668265263 + s * 1274126177; h = (h xor (h ushr 13)) * 1274126177; return ((h xor (h ushr 16)) and 0xFFFF) / 32767.5f - 1f }
        val a = r(x0, y0); val b = r(x0 + 1, y0); val c = r(x0, y0 + 1); val d = r(x0 + 1, y0 + 1)
        return (a + (b - a) * u) + ((c + (d - c) * u) - (a + (b - a) * u)) * v
    }

    companion object {
        fun lerp(a: Int, b: Int, t: Float): Int {
            val k = t.coerceIn(0f, 1f)
            fun ch(s: Int) = (((a ushr s) and 0xFF) * (1 - k) + ((b ushr s) and 0xFF) * k).toInt()
            return (0xFF shl 24) or (ch(16) shl 16) or (ch(8) shl 8) or ch(0)
        }
        fun darken(c: Int, f: Float): Int {
            fun ch(s: Int) = (((c ushr s) and 0xFF) * f).toInt().coerceIn(0, 255)
            return (c and 0xFF000000.toInt()) or (ch(16) shl 16) or (ch(8) shl 8) or ch(0)
        }
    }
}
