package com.sengine.project

/**
 * Ultimate Edition Pro pixel-art library. Every sprite is authored as 16×16 character rows so the
 * whole catalogue can be generated and validated on the JVM (no android.graphics needed).
 *
 * Row characters: '.' transparent, 'o' outline, 'w' white highlight, 'g' glow — plus any palette
 * characters the item defines ('a'/'A' primary/shade, 'b'/'B' secondary/shade, 'c' accent...).
 */
internal object ForgeArt {
    val arts = LinkedHashMap<String, List<String>>()

    private fun a(name: String, rows: String) {
        arts[name] = rows.trimIndent().split('\n').map { it.padEnd(16, '.') }.map { it.take(16) }
    }

    init {
        a("gem", """
................
................
................
.....oooooo....
....oawaaao....
...oaaaaacaao...
...oaaaaacaao...
...oAaaaaaaAo...
....oAaaaaAo....
.....oAaaAo.....
......oAao......
.......oo.......
................
................
................
................
""")

        a("potion", """
................
.....ooooo......
.....ow..o......
.....o....o.....
....oaaaaao.....
...oaaaaaaao....
...oaaaaaaaaao..
...oawaaaaaao......oAaaaaaaAo...
....oAaaaaAo....
.....oAaaAo.....
......oooo......
.....o....o.....
.....o....o.....
......oooo......
................
""")

        a("key", """
................
................
....oooo........
...oawwao.......
...oa..ao.......
...oa..ao.......
...oa..ao.......
...oa..ao.......
...oa..ao.......
...oa..ao.......
...oawwaaaao....
...oaaaaaaao....
...oaaooaao.....
....oo..oo......
................
................
""")

        a("sword", """
..........oo...
.........owao..
........owao...
.......owao....
......owao.....
.....owao......
..o.owao.......
..ooaao........
..ooao.........
.oaoao.........
ooo..o.oo......
........o......
.......oo......
......oMo......
.....oMMMo.....
......ooo......
""")

        a("shield", """
................
...ooooooooo....
..oawaaaahaao...
..oaaaaaaaao....
..oaaacaaacao...
..oaaaccaacao...
..oaaacaaacao...
..oaaaaaaaao....
..oAaaaaaaao....
...oAaaaaao.....
....oAaao.......
.....oao........
......o.........
................
................
................
""")

        a("bow", """
................
....ooooo.......
...oab..wao.....
..oab....oao....
..ob......oao...
..ob......oao...
..ob......oao...
..ob......oao...
..ob......oao...
..oab....oao....
...oab..oao.....
....ooooo.......
.......oc.......
.......oc.......
.......oc.......
................
""")

        a("axe", """
................
....oooo........
...obbbbo.......
..obbabbbo......
..obabbbbo......
..obbbbbo.......
...oobboo.......
....oaao........
....oaao........
....oaao........
....oaao........
....oaao........
...oMMMo........
....ooo.........
................
................
""")

        a("hammer", """
................
...ooooooo......
..ommmmmmmo.....
..omwmmmmmo.....
..ommmmmmmo.....
...ooooooo......
.....oaao.......
.....oaao.......
.....oaao.......
.....oaao.......
.....oaao.......
.....oaao.......
....oMMMo.......
.....ooo........
................
................
""")

        a("wand", """
................
..........og....
.........ogggo..
..........og....
.....o....o.....
....oao..oao....
....oao..oao....
.....oaoaoao....
......oaao......
......oaao......
.......oo.......
................
................
................
................
................
""")

        a("staff", """
................
.......ogo......
......oggo......
.......ogo......
.......oao......
.......oao......
.......oao......
.......oao......
.......oao......
.......oao......
.......oao......
.......oao......
.......oao......
......oMMo......
.......oo.......
................
""")

        a("spear", """
................
..........oo....
.........oaao...
..........oo....
.........oao....
........oao.....
.......oao......
......oao.......
.....oao........
....oao.........
...oao..........
..oao...........
.oMo............
..o.............
................
................
""")

        a("helmet", """
................
................
....oooooo......
...oaaaaaao.....
..oaaaaaaaaao...
..oawaaaaaaao...
..oaooaaooao....
..oaaaoaaao.....
..oaaaaaaaaao...
..oAaaaaaaao....
...oAooooAao....
....oo....o.....
................
................
................
................
""")

        a("crown", """
................
................
................
................
...oo.oo.oo.....
..owaoeaoweao...
..oaeaeeeeaeao..
..oeeeeeeeeeo...
..oeg ege ego...
..oeeeeeeeeeo...
..oeeeeeeeeeo...
...oooooooo.....
................
................
................
................
""")

        a("hat", """
................
................
................
......oo........
.....oao........
....owao........
....oaao........
...oaaaao.......
..oaaaaaao......
.oaaaaaaaaao....
oaaaaaaaaaaao...
.ooooooooooo....
................
................
................
""")

        a("armor", """
................
....oo...oo.....
...oaaaaaaao....
..oaaawaaawao...
..oaaaaaaaaao...
..oaoaaaaaoao...
..oaoaawaaoao...
..oaoaaaaaoao...
...oaaaaaaao....
...oAaaaaaao....
...oAaaaaaao....
...oAoooooao....
....oo...oo.....
................
................
................
""")

        a("boots", """
................
................
................
................
...ooo...ooo....
..oaaao.oaaao...
..oaaao.oaaao...
..oaaao.oaaao...
..oaaaoooaao....
..oaaaaaaaao....
..oAAAAAAAAao...
..ooooooooooo...
................
................
................
................
""")

        a("ring", """
................
................
................
......cggo......
.....og..go.....
....og....go....
....og....go....
....og....go....
.....og..go.....
......cggo......
................
................
................
................
................
................
""")

        a("amulet", """
................
.....oooo.......
....o....o......
....o....o......
.....oooo.......
....oaawao......
...oaaaaaaao....
...oaacccaao....
...oaaaaaaao....
....oaawao......
.....oooo.......
................
................
................
................
................
""")

        a("book", """
................
................
...oooooooooo...
..oaaaaaaaaaao..
..oabbbbbbbbao..
..oabwwbbbbbao..
..oabbbbbbbbao..
..oabbbwwbbbao..
..oabbbbbbbbao..
..oabwwbbbbbao..
..oabbbbbbbbao..
..oAaaaaaaaaAo..
..oooooooooooo..
................
................
................
""")

        a("scroll", """
................
................
...oooooooooo...
..owwwwwwwwwo...
..owwwwwwwwwo.o.
..ow.wwwwww.oo..
..owwwwwwwwoo...
..ow.wwwwww.o...
..owwwwwwwwo....
..ow.wwwww.o....
..owwwwwwwwo....
..oooooooooo....
...o......o.....
...oooooooo.....
................
................
""")

        a("bomb", """
................
.........ogo....
........oo......
.......oaao.....
......oo........
.....ooooo......
....oaaaaao.....
...oaaaaaaaao...
..oaaawaaaaao...
..oaaaaaaaaao...
..oAaaaaaaaao...
..oAAaaaaaaAo...
...ooAAAAAoo....
................
................
................
""")

        a("dynamite", """
................
................
.....oooooo.....
.....orrrro.....
.....orwrrOo....
.....orrrro.....
.....orrrro.....
.....orrrro.....
.....orrrro.....
.....orrrro.....
.....orrrro.....
.....oooooo.....
......oggo......
.......oo.......
................
................
""")

        a("barrel", """
................
................
...oooooooooo...
..ommvmvmvmmo...
..oMMMMMMMMMo...
..omvmvmvmvmo...
..oMMMMMMMMMo...
..omvmvmvmvmo...
..oMMMMMMMMMo...
..omvmvmvmvmo...
..oMMMMMMMMMo...
...oooooooooo...
................
................
................
................
""")

        a("crate", """
................
................
...oooooooooo...
..owoodowooowo..
..ooooowoooooo..
..owoowooowoowo.
..oooowoooowooo.
..oowooowoowoow.
..oooowoooowooo.
..owoowoowoowoo.
..ooowoooowoooo.
..oAooooooooAo..
...oooooooooo...
................
................
................
""")

        a("chest", """
................
................
...oooooooooo...
..oAAAAAmAAAo...
..oaaaaaaaaao...
..oaaaaaaaaao...
..oooooooooooo..
..oaaaogoaaao...
..oaaaogoaaao...
..oaaaogoaaao...
..oAAAogoAAAo...
..oAAAAmAAAAo...
...oooooooooo...
................
................
................
""")

        a("door", """
................
...ooooooooo....
..oaaaaaaaaao...
..oaaaaaaaao....
..oabbabbaao....
..oabbabbaao....
..oabbabbaao....
..oabbabbaao....
..oabbabbaao....
..oabbabbaao....
..oabbabbaao....
..oAaaaaaaaAo...
..oAAAgAAAAo....
...oooooooo.....
................
................
""")

        a("ladder", """
................
..oo.......oo...
..oao.....oao...
..ooooooooooo...
..oao.....oao...
..oao.....oao...
..oo.......oo...
..oo.......oo...
..oao.....oao...
..ooooooooooo...
..oao.....oao...
..oao.....oao...
..oo.......oo...
..oo.......oo...
................
................
""")

        a("sign", """
................
................
...oooooooooo...
..owwwwwwwwwo...
..ow.o.owwww.o..
..owwwwwwwww.o..
..ow.ow.owww.o..
..owwwwwwwww....
..owww.owwww....
...oooooooooo...
.......oao......
.......oao......
.......oao......
......oMMMo.....
................
................
""")

        a("flag", """
................
....o...........
....oaoooooooo..
....oaaaaaaaao..
....oaaaawaaao..
....oaaaaaaaao..
....oaawaaaaao..
....oaaaaaaaao..
....oAaaaaaaao..
....oAaaaaaao...
....oAoaaao.....
....o..oao......
.......oao......
......oMMo......
.......oo.......
................
""")

        a("torch", """
................
................
.......gg.......
......gwwg......
......wgwg......
.......ww.......
......wwww......
.......aa.......
.......aA.......
.......aA.......
.......aA.......
.......aA.......
......oMMo......
.......oo.......
................
................
""")

        a("lantern", """
................
......oo........
.....o..o.......
....oooooooo....
....oaaaaaao....
....oagwgaao....
....oawggwao....
....oagwgaao....
....oaaaaaao....
....oAAAAAo.....
.....ooooo......
......o..o......
......oo........
................
................
................
""")

        a("anvil", """
................
................
................
...oooooooooo...
..ommmmmmmmmmo..
..omwmmmmmmmmo..
...oommmmmoo....
.....ommmo......
.....ommmo......
....ommmmmo.....
...ommmmmmmo....
...oooooooooo...
................
................
................
................
""")

        a("bell", """
................
......oo........
.....oaao.......
....oaaaao......
....oaaaao......
...oaaaaaao.....
...oaaaaaao.....
...oaaaaaao.....
..oaaaaaaaao....
..oaaaaaaaaao...
..ooooooooooo...
......ogo.......
.......o........
................
................
................
""")

        a("bag", """
................
......oo........
.....o..oo......
....o.oo.o......
....oaawao......
...oaaaaaao.....
..oaaaaaaaao....
..oaaaaaaaaao...
..oaaaaaaaaao...
..oAaaaaaaaao...
..oAAAAAAAAAo...
...ooooooooo....
................
................
................
""")

        a("bone", """
................
................
................
..ooo......ooo..
.oawwao..oawwao.
.oawwwaooawwwao.
..oawwoowwoao...
...oooaaoaoo....
......oao.......
.....oawwao.....
.oawwoowwoao....
.oawwwaooawwwao.
.oawwao..oawwao.
..ooo......ooo..
................
................
""")

        a("skull", """
................
................
................
...ooooooooo....
..oaaaaaaaaao...
..oaaaaaaaaao...
..oaoowwooao....
..oaoooooooao...
..oaoowwooao....
..oaaaaaaaaao...
...oaoaoaoao....
...oaoaoaoao....
....ooooooo.....
................
................
................
""")

        a("mushroom", """
................
................
....oooooo......
..ooaaaaaaoo....
..oawaaaaaaao...
.oaaaaaaaaaaao..
.oaaaowaaaaaao..
.oaaaaaaaaaaao..
..ooAooooAoo....
....owwwwo......
....owwwwo......
....owwwwo......
....owwwo.......
.....ooo........
................
................
""")

        a("flower", """
................
.......oa.......
......oao.......
...oo.ocAco.....
..oawoccccao....
..oawoccccao....
...oo.ocAco.....
......oao.......
....oaoaoaoo....
...oaaooaao.....
.....oaoao......
......oa........
......oa........
.....oMMo.......
......oo........
................
""")

        a("cactus", """
................
.....ooo........
....oaaao.ooo...
....oawaooabao..
..oooaaoabao....
.oabaaoaaboo....
.oabaaaoaao.....
..ooabaaoao.....
....oaaaoao.....
....oawaoao.....
....oaaaoao.....
...oAaaaAao.....
...oAAAAAAo.....
....ooooo.......
................
................
""")

        a("bush", """
................
................
................
....oooooo......
..ooaaaaaaoo....
.oawaaaaaaaao...
.oaaaaaaaaaaao..
oaaaaaaaaaaaaao.
oaaaawaaaaaaaao.
oaaaaaaaaaaaaao.
.oAaaaaaaaaaAo..
..ooAAAAAAAAoo..
....ooooooo.....
................
................
................
""")

        a("pine", """
................
......oo........
.....oaao.......
....oaaaao......
...oaaaaaao.....
.....oaao.......
....oaaaao......
...oaaaaaao.....
..oaaaaaaaao....
.....oaao.......
....oaaaaao.....
...oaaaaaaaao...
..oaaaaaaaaaao..
......oMo.......
.....oMMMo......
......ooo.......
""")

        a("tree", """
................
....oooooo......
..ooaaaaaaoo....
.oawaaaaaaaaao..
.oaaaaaaaaaaaao.
oaaaaaaaaaaaaaao
oaaaawaaaaaaaaao
oaaaaaaaaaaaaaao
.oaaaaaaaaaaaao.
.oaaaaaaaaaaaao.
..ooaaaaaaaoo...
....ooaaaoo.....
......oMo.......
......oMo.......
.....oMMMo......
......ooo.......
""")

        a("palm", """
................
..o..........o..
..ao........oa..
..oaao....oaao..
...oaao..oaao...
....oaaoaao.....
.....oaaco......
......oco.......
......oco.......
......oco.......
......oco.......
......oco.......
.....oMMo.......
....oMMMmo......
.....ooo........
................
""")

        a("rock", """
................
................
................
................
.....oooo.......
....oaawaoo.....
..ooaaaaaaaoo...
..oaaaaawaaao...
.oaaaaaaaaaaao..
.oaaaaawaaaaao..
.oaaaaaaaaaaao..
.oAaaaaaaaaaAo..
..ooAAAAAAAoo...
....ooooooo.....
................
................
""")

        a("slime", """
................
................
................
................
.....oooooo.....
...ooaaaaaaoo...
..oaaaaawaaaao..
..oawaaaaaaaao..
.oaaoaaaaoaao...
.oaaoooooooaao..
.oaaaaaaaaaaao..
.oaaaaaaaaawa o.
.oAaaaaaaaaaAo..
..ooAAAAAAAAoo..
...ooooooooo....
................
""")

        a("bat", """
................
................
................
..o..........o..
.obo........obo.
.obbo..oo..obbo.
.obbbobaaobbbbo.
..obbaaaaabbbo..
...oaaaaaaaao...
...oaoaaoaoao...
....oaaoaao.....
.....o.oo.o.....
................
................
................
................
""")

        a("ghost", """
................
................
.....ooooo......
...ooaaaaaoo....
..oaaawaaawao...
..oaaaaaaaaao...
..oaaaaaaaaao...
..oaaaaaaaaao...
..oaaaaaaaaao...
..oaaaaaaaaao...
..oaaaaaaaaao...
..oaoaaoaaoao...
...oo.oo.oo.....
................
................
................
""")

        a("spider", """
................
................
.o..o......o..o.
.oboobo..oboobo.
..oobbooobboo...
..obbaaaaaabb...
...oawaaaawao...
..oaaaoaoaaaao..
.obbaaaaaaabbo..
..oobboooobboo..
.o..o......o..o.
................
................
................
................
................
""")

        a("rat", """
................
................
................
................
......oo..oo....
.....oaoooaao...
..oooaawaaaao...
.oaaaaaaaaaaao..
oaaaaaaaaaaaao..
oaaaoaaaoaaaao..
.oooooooooooo...
..oo..oo..oo....
................
................
................
................
""")

        a("snake", """
................
................
................
................
..........oo....
.....oo..oaao...
....oaooaawao...
....oawaaoao....
.....oaoao......
....oaao........
....oao.........
.....oao........
.....oaoo.....
......oooo......
................
................
""")

        a("crab", """
................
................
................
..o..........o..
..obo..oo..obo..
..oobooaaooboo..
...oaaaaaaaao...
..oaawaaaawao...
..oaaaoaoaaaao..
.obbaaaaaaabbo..
.oobbooooobboo..
.o..ooooooo..o..
................
................
................
................
""")

        a("bee", """
................
................
................
......ooo.......
.....oaaaao.oo..
..oooaawaaaoyo..
.oyyoaaaaaaoyo..
..oooaawaaao....
.....oaaaao.oo..
......ooo.......
................
.......o.o......
................
................
................
................
""")

        a("fish", """
................
................
................
................
......ooooo.....
....ooaaaaao....
...oawaawaaao...
..oaaaaaaaaao...
..oaaaoaaaaao...
...oaaawaaaao...
....ooaaaaao....
......ooooo.....
................
................
................
................
""")

        a("shark", """
................
................
................
................
..oo........oo..
.oaaooooooooaao.
oawaaaaaaaaawao.
oaaaaaaaaaaaaao.
oaoaoaaaaaoaoao.
.oaaoooooooaao..
...oo......oo...
................
................
................
................
................
""")

        a("bird", """
................
................
................
.......oo.......
......oaao......
.....oaawaao....
.....oaaaaao....
......oaaao.....
......oaao......
.....oaao.......
....oaao........
....oo..........
................
................
................
................
""")

        a("butterfly", """
................
................
................
..ooa......aoo..
.oaaao.oo.oaaao.
.oaaaaoaaaoaaao.
.oaaaaoaaaoaaao.
..oaaaaoaoaaao..
...ooaaooaaoo...
.....oa..ao.....
......o..o......
................
................
................
................
................
""")

        a("owl", """
................
................
...oooo..oooo...
..oaaaaoaaaaaao.
..oawaoaaaoawao.
..oaoaoaaaoaoao.
..oaaaoaaaaoao..
..oaaaaawaaaao..
..oaaaaawaaaao..
...oaaaawaaao...
....oooooooo....
.....oao.oao....
......oo.oo.....
................
................
................
""")

        a("knight", """
................
.....oooo.......
....oaaaao......
....ossssso.....
...ooaaaoo......
..oaaawaaao.....
..oaoaaaao......
..oaoaaaao.s....
..oaoaaaaoao....
...oaaawao......
....oaaaao......
....oa.ao.......
....oa.ao.......
....oo.oo.......
................
................
""")

        a("mage", """
................
......oo........
.....oaao.......
....owaaawo.....
...oaaaaaaao....
...oaaoaoao.....
....ossssso.....
...oabbbbaoo....
..oababbbbao....
..oaobbbbao.....
..oaoabbao......
...oaoaoao......
....o...o.......
....o...o.......
...oo...oo......
................
""")

        a("archer", """
................
.....oooo.......
....ossssso.....
.....ossso......
...ooaaaoo......
..oaawaaaao.oo..
..oaoaaaao.owbo.
..oaoaaaao.owbo.
..oaoaaaao.oo...
...oaaaao.......
....oaaaao......
....oa.ao.......
....oa.ao.......
....oo.oo.......
................
................
""")

        a("rogue", """
................
.....oooooo.....
....oaaaaaao....
.....osssso.....
...ooawaoo......
..oaaawaaaao....
..oaoaaaao......
..oaoaaaao.m....
..oaoaaaaoamo...
...oaaawao.oo...
....oaaaao......
....oa.ao.......
....oa.ao.......
....oo.oo.......
................
................
""")

        a("barbarian", """
................
.....o..o.......
....ossssso.....
....ossssso.....
..ooowawoo......
..oaaawaaao.....
..oaoaaaao.oo...
..oaoaaaaoowbo..
..oaoaaaaoowbo..
...oaaawao.oo...
....oaaaao......
....oa.ao.......
....os.so.......
....oo.oo.......
................
................
""")

        a("necromancer", """
................
.....oooo.......
....ohhhho......
....owwwwwo.....
...oohhhoo......
..ohhhhhhho.....
..ohohhhho.w....
..ohohhhho.mo...
..ohohhhhoamo...
...ohhhhwao.....
....ohhhho......
....oh.ho.......
....oh.ho.......
....oo.oo.......
................
................
""")

        a("pirate", """
................
....oooooo......
...ohhhhhho.....
.....ossso......
...ooawaoo......
..oarrrrrao.....
..oaorrrao......
..oaorrrao.m....
..oaorrraoamo...
...oarrrao.oo...
....oorroo......
....os.so.......
....oo.oo.......
................
................
................
""")

        a("orc", """
................
...oo......oo...
..oggo....oggo..
..ogggooooogggo.
...oggggsggggo..
....ogsgsssgo...
...oogsgsggoo...
..oggggggggggo..
..ogogggggogo...
..ogogggggogo...
...ogggrgggo....
....oggoggo.....
....og..go......
....oo..oo......
................
................
""")

        a("goblin", """
................
..oo........oo..
..obo....oobo...
..obo.oo.oboo...
...obggggobo....
....ogsgsgo.....
...oogsggoo.....
..oggggggggo....
..ogoggggogo....
...ogggrggo.....
....oggggo......
....og.ogo......
....oo..oo......
................
................
................
""")

        a("troll", """
................
..oooo....oooo..
..ogggo..ogggo..
..oggggooogggo..
...ogggggggggo..
...ogsgsssggo...
..oogsgsgggoo...
.oggggggggggggo.
.ogogggggggogo..
.ogogggggggogo..
..ogggrwrgggo...
...ogggggggo....
...ogg..ggo.....
...oo....oo.....
................
................
""")

        a("skeleton", """
................
.....oooo.......
....owwwwwo.....
....owowowo.....
.....owwwo......
......oo........
...owwwwwwo.....
..owowwwwowo....
..owowwwwowo....
...owwwwwwo.w...
....owwwowwoo...
....ow.wowo.....
....ow.owo......
....oo.oo.......
................
................
""")

        a("zombie", """
................
.....oooo.......
....oggggo......
....ogogogo.....
.....oggo.......
...oooggooo.....
..oggoggggo.....
..ogoggoggoo....
..ogoggggggo....
...oggggwgo.....
....oggggo......
....og..go......
....og..go......
....oo..oo......
................
................
""")

        a("mummy", """
................
.....oooo.......
....owwswso.....
....owswswo.....
.....osso.......
...ooowwooo.....
..owwowwwwwo....
..owowwowowo....
..owowwowowo....
...owwowwwo.....
....owwwwo......
....ow..wo......
....ow..wo......
....oo..oo......
................
................
""")

        a("imp", """
................
..o..........o..
..oo....o..oo...
...oo.roro.oo...
....orrrrrro....
....owowowo.....
...oorrrrroo....
..orrrrrrrrro...
..ororrrrroro...
...orrrrrrro....
....orrrrro.....
....or..ro......
....or..ro......
....oo..oo......
................
................
""")

        a("demon", """
................
..oo........oo..
..oro..o..oro...
..orr.oro.rro...
...orrrrrrro....
....owowowo.....
...oorrrrrroo...
..orrrwrrrrrro..
..ororrrrroro...
..ororrrrroro...
...orrrrrrro....
....orrrrro.....
....or..ro......
....oo..oo......
................
................
""")

        a("dragonling", """
................
................
.....ooro.......
....oorrro......
...orrrorrro....
..orrorwrrrro...
.oorrooorrroo...
orrro.oorrroro..
orro..orrrro....
.or....orwro....
.......orro.....
........oroo....
.........oo.....
................
................
................
""")

        a("golem", """
................
....oooooo......
...ommmmmmo.....
...omwmmwmo.....
...oommmoo......
..oommmmmmoo....
.ommoMMMMommo...
.ommoMMMMommo...
.ommoMMMMommo...
..ooMMMMMMoo....
...oMMooMMo.....
...oMMooMMo.....
...ooo..ooo.....
................
................
................
""")

        a("robot", """
................
....oooooo......
...ommmmmmo.....
...omg..gmo.....
...oooooo o.....
....ommmmo......
..oommmmmmoo....
.ommogwwgommo...
.ommoMMMMommo...
..ooMMMMMMoo....
...oMMMMMMo.....
...oMMo.oMo.....
...ooo..ooo.....
................
................
................
""")

        a("droid", """
................
......oooo......
.....ommmmo.....
.....omg.gmo....
.....oooooo.....
......ommo......
....oommmooo....
...ommmmmmmmo...
...omooooomo....
....oommmoo.....
.....ommmo......
....oo.oo.......
................
................
................
................
""")

        a("mech", """
................
..oo........oo..
..omo.oooo.omo..
..omoommmmoomo..
...oomgwwgmoo...
....ommmmmmo....
..oommmmmmmmoo..
.ommoMMMMMoMMmo.
.ommoMMMMMoMMmo.
..ooMMMMMMMMoo..
...oMMoooMMo....
...oMMo.oMMo....
..oMMo...oMMo...
..ooo.....ooo...
................
................
""")

        a("alien", """
................
.....ooooo......
....oaaaaao.....
...oaaaaaaao....
...oaoawaoao....
...oaaaaaaao....
....oawaao......
.....oooo.......
....oggggo......
...ogggggggo....
...ogogggogo....
....oggggo......
....og..go......
....oo..oo......
................
................
""")

        a("ufo", """
................
................
................
......oooo......
.....obbbbo.....
....obggggbo....
...obbbbbbbbo...
..ooooooooooo o.
..ogogogogogogo.
...oooooooooo...
....oo....oo....
................
................
................
................
................
""")

        a("rocket", """
................
.......oo.......
......owwo......
......oaao......
.....oaawao.....
.....oaawao.....
.....oaaaaao....
.....oabaao.....
.....oabaao.....
....ooabaoo.....
....ogabago.....
....oggaaggo....
.....oggggo.....
......oggo.......
.......oo.......
................
""")

        a("satellite", """
................
.oo..........oo.
.oaao..ooo..oaao.
.oaaooommmoooao.
..ooommmmmmooo..
....omgwwgmo....
....oommmmoo....
......ommo......
.......oo........
......oao.......
.....oaaaaao....
....ooooooooo...
................
................
................
................
""")

        a("apple", """
................
........ogo.....
.......oo.......
....oooaooo.....
..oaaaaaaao.....
.oawaaaaaaao....
.oawaaaaaaaao...
.oaaaaaaaaaao...
.oaaaaaaaaaao...
.oaaaaaaaaaco...
.oAaaaaaaaaAo...
.oAAaaaaaaaAo...
..ooAAAAAAAo....
....oooooo......
................
................
""")

        a("banana", """
................
................
.......ooo......
......owwo.o....
.....oaao.oo....
....oaao........
...oabao........
..oaabao........
..oaabo.........
..oabbo.........
..oabbo.........
..ooabboo.......
....ooaao.......
......ooo.......
................
................
""")

        a("carrot", """
................
..........oo....
......oo.oao....
....oogggao.....
......oogggo....
.......oaao.....
......oaawao....
......oawao.....
.......oaao.....
.......oaao.....
......oaao......
......oao.......
.......oo.......
................
................
................
""")

        a("bread", """
................
................
................
....oooooo......
..ooabbbbboo....
..oabwwbbbbao...
.oabbbbbbbbao...
.oabwwbbbbbbao..
.oabbbbbbbbbao..
.oAaaaaaaaaaAo..
.oAAAAAAAAAAAo..
..ooooooooooo...
................
................
................
................
""")

        a("cheese", """
................
................
................
................
....ooooooo.....
..ooawaaaaaao...
.oaaaoaaaaaaao..
.oaaaaaoaaaaao..
.oaaaaaaaoaaao..
.oAaaaaaaaaoAo..
..ooAAAAAAAoo...
....ooooooo.....
................
................
................
................
""")

        a("meat", """
................
................
................
....ooooo.......
...oaaaaaoo.....
..oaaawaaaao....
..oawaaaaaao....
..oaaaawaaao....
...oaaaaaao.....
....owwwwo......
.....owwo.......
......oo........
................
................
................
................
""")

        a("egg", """
................
................
................
......oooo......
.....owwao......
....owaawaao....
....oaaaaaao....
....oaaaaaao....
....oaaaaaao....
.....oaaaao.....
......oooo......
................
................
................
................
................
""")

        a("milk", """
................
................
.....oooo.......
.....o..o.......
.....owwo.......
....oooooo......
....oaaaaao.....
....owwwwo......
....owggwo......
....owwwwo......
....owwwwo......
....owwwwo......
....oooooo......
................
................
................
""")

        a("coffee", """
................
................
................
....oooooo......
....oaaaaao.....
...oooooooooo...
...oaaaaaaaao...
...oawwaaaaao...
...oaaaaaaaao...
...oAaaaaaaaAo..
....oooooooo....
......o..o......
......oooo......
................
................
................
""")

        a("cake", """
................
......w.w.......
.....owowow.....
....oooooooo....
....orrrrrro....
...oRrrrrrrRo...
...oooooooooo...
...oawaaaaaao...
...oaaaaaaaaao..
..oaaaaaaaaaaao.
..oAaaaaaaaaaAo.
..oooooooooooo..
................
................
................
................
""")

        a("corn", """
................
.....o..o.......
....oyooyo......
...oyyyyyyo.....
...oywyyyyo.....
...oyyyyyyo.....
...oyywyyyo.....
...oyyyyyyo.....
....oyyyyo......
.....oyyo.......
.....oggo.......
....oggggo......
.....oggo.......
......oo........
................
................
""")

        a("pumpkin", """
................
.......ogo......
........o.......
....oooooooo....
..ooaaaaaaaoo...
.oawaaoaaaawao..
.oaaaoaaaaaaao..
.oaaaaaaaaaaao..
.oaaaoaaaaaaao..
.oaaaaaaaaaaao..
.oAaaaaaaaaaaAo.
.oAAooooooooAAo.
..ooooooooooo...
................
................
................
""")

        a("berry", """
................
.......ogo......
........oo......
....oo.oo.oo....
...oaaoaaaoao...
..oaaaaaaawao...
..oawaaaaaaao...
..oaaaaaaawao...
..oawaaaaaaao...
...oaaaaaaao....
....ooaaaoo.....
......ooo.......
................
................
................
................
""")

        a("compass", """
................
................
................
....oooooooo....
..oawaaaaaaaao..
..oaaaowoaaaao..
..oaaaawwoaaaao.
..oaaaaowwoaaao.
..oaaaaaowaaaao.
..oaaaaaaaaaaao.
...oooooooooo...
................
................
................
................
................
""")

        a("map", """
................
................
...oooooooooo...
..owwwwwwwwwo...
..owwwowwwwwo.o.
..ow.wwwwww.oo..
..owwwwowwwwo...
..ow.wwwwww.o...
..owwowwwwwwo...
..ow.wwwww.o....
..owwwwwwwwo....
..oooooooooo....
...o......o.....
...oooooooo.....
................
................
""")

        a("treasure", """
................
...og.....go....
..oggg.oggggo...
..ogegoegoego...
.ogeggeeggeego..
.oeggeeeeggeeo..
.ogeegwwweeggo..
.ogegeeeeggego..
.oggeeeeeegggo..
..ogeeeeeeego...
..oggeeeeeggo...
...ooooooooo....
................
................
................
................
""")

        a("gear", """
................
................
......oooo......
.....omwwmo.....
...ooommmmooo...
..omoommmmoomo..
..ommmmmmmmmmo..
..ommmmmmmmmmo..
..omoommmmoomo..
...ooommmmooo...
.....ommmmo.....
......oooo......
................
................
................
................
""")

        a("battery", """
................
................
.....oooo.......
.....oggo.......
...oooooooooo...
...oaaaaaaaao...
...oaawwaaaao...
...oawwwwwaao...
...oawwwwwaao...
...oaawwaaaao...
...oaaaaaaaao...
...oAaaaaaaa o..
...oooooooooo...
................
................
................
""")

        a("chip", """
................
................
....o.o.o.o.....
...oooooooooo...
...oaaaaaaaao...
.o.oawaaaaaao.o.
...oaaaaaaaao...
.o.oaaaaaaaao.o.
...oaaaaaaaao...
.o.oAaaaaaaaAo.o
...oAaaaaaaaAo..
...oooooooooo...
....o.o.o.o.....
................
................
................
""")

        a("ore", """
................
................
................
....oooo........
...oaaaoo.......
..oawaaaaoo.....
..oaaaagaaoo....
..oaaaggaaaao...
...oaaagaaao....
....ooaaaoo.....
......oooo......
................
................
................
................
................
""")

        a("anchor", """
................
......oo........
.....oggo.......
......oo........
...oooooooooo...
...oo..oo..oo...
......oao.......
......oao.......
......oao.......
......oao.......
...oooooooooo...
..oooooooooooo..
................
................
................
................
""")

        a("bucket", """
................
................
....oooooooo....
...o........o...
..oaaaaaaaaaao..
..oawaaaaaaaao..
..oaaaaaaaaaao..
..oaaaaaaaaaao..
...oaaaaaaaao...
...oaaaaaaaao...
....oooooooo....
................
................
................
................
................
""")

        a("rope", """
................
................
.....oooo.......
....o....o......
....o.oo.o......
....oo..oo......
....o.oo.o......
....oo..oo......
....o.oo.o......
....oo..oo......
....o.oo.o......
.....oooo.......
................
................
................
................
""")

        a("feather", """
................
..........oo....
.........owao...
........owwao...
.......owwwao...
......owwwwao...
.....owwwwwao...
.....owwwwao....
....owwwwao.....
....owwwao......
....owwao.......
....owao........
....ooo.........
................
................
................
""")

        a("heart", """
................
................
................
...ooo...ooo....
..oaawo.oawao...
..oawaaoawaao...
..oaaaaawaaao...
..oaaaaaaaaao...
...oaaaaaaao....
....oaaaaao.....
.....oaao.......
......oo........
................
................
................
................
""")

        a("star", """
................
.......oo.......
......oaao......
......oaao......
..ooooaaaaooo...
.oaaaaawaaaaao..
..oaaaaaaaaao...
...oaaaaaaao....
..oaaaaaoaaaao..
.oaaao.....oaao.
.oao.........oao
..o...........o.
................
................
................
................
""")

        a("planet", """
................
................
.....oooooo.....
...ooaaaaaaoo...
..oaaaabbbaaao..
..oawabaababao..
..oaaabbbbaaao..
..oaaaabbaaaao..
...oaaabaaaao...
....oooooooo....
................
................
................
................
................
................
""")

        a("moon", """
................
................
.....oooo.......
....oaaaao......
...oawaaaao.....
...oaaaaaaao....
...oaaaaaao.....
...oaaaaaaao....
....oaaaaao.....
.....ooooo......
................
................
................
................
................
................
""")

        a("sun", """
................
................
.......gg.......
......oggo......
...g.ogwwgo.g...
....ogwwwwgo....
..ggowwwwwwogg..
....ogwwwwgo....
...g.ogwwgo.g...
......oggo......
.......gg.......
................
................
................
................
................
""")

        a("comet", """
................
................
..........oo....
.........owao...
........owaaoo..
.......owaaao...
......owaaao....
.....ogwaao.....
....ogggo.......
...ogggo........
..oggo..........
..oo............
................
................
................
................
""")

        a("orb", """
................
................
................
.....oooo.......
....oaaaao......
...oawaaaao.....
...oawaaaao.....
...oaaaaaao.....
....oaaaaao.....
.....oaaao......
......ooo.......
................
................
................
................
................
""")

        a("frame", """
oooooooooooooooo
owwwwwwwwwwwwwwo
owoooooooooooowo
ow oooooooooo wo
ow oaaaaaaaaa wo
ow oaagaaaaga wo
ow oaaaaaaaaa wo
ow oaagaaaaaga wo
ow oaaaaaaaaa wo
ow oaaagaagaa wo
ow oaaaaaaaaa wo
ow oooooooooo wo
owwwwwwwwwwwwwwo
oooooooooooooooo
................
................
""")

        a("button", """
................
................
..oooooooooooo..
.oawwwwwwwwwwwo.
.oaaaaaaaaaaaao.
.oaaaaaaaaaaaao.
.oaaaaaaaaaaaao.
.oaaaaaaaaaaaao.
.oAAAAAAAAAAAAo.
..oooooooooooo..
................
................
................
................
................
................
""")

        a("panel", """
oooooooooooooooo
owwwwwwwwwwwwwwo
owaaaaaaaaaaaa wo
ow aaaaaaaaaa wo
ow aaaaaaaaaa wo
ow aaaaaaaaaa wo
ow aaaaaaaaaa wo
ow aaaaaaaaaa wo
ow aaaaaaaaaa wo
ow aaaaaaaaaa wo
ow aaaaaaaaaa wo
ow aaaaaaaaaa wo
owAAAAAAAAAAAAwo
oooooooooooooooo
................
................
""")

        a("check", """
................
................
..oooooooooo....
..oaaaaaaaaao...
..oaaaaaaaaao...
..oaaaaaaaaao...
..oaaaaaaaaao...
..oaaaaaaaaao...
..oaaaaaaaaao...
..oaaaaaaaaao...
..oAAAAAAAAAo...
...ooooooooo....
................
................
................
................
""")

        a("checkOn", """
................
................
..oooooooooo....
..oaaaaaaaaao...
..oagaawaaao....
..oaagaawaaao...
..oaagaagaawo...
..oaaagaagaao...
..oaaaagaagao...
..oaaaaagaaao...
..oAaaaaaaaaAo..
...ooooooooo....
................
................
................
................
""")

        a("sliderTrack", """
................
................
................
................
..oooooooooooo..
.oaaaaaaaaaaaao.
.oAAAAAAAAAAAAo.
..oooooooooooo..
................
................
................
................
................
................
................
................
""")

        a("sliderThumb", """
................
......oooo......
.....oawwao.....
....oawwwwao....
....oawwwwao....
....oawwwwao....
.....oawwao.....
......oooo......
................
................
................
................
................
................
................
................
""")

        a("ice", """
................
................
......oo........
.....owgo.......
....owggwo......
....ogwwgo......
...owwwwwwo.....
...ogwwwgo......
....ogwgo.......
....owgwo.......
....oggo........
.....oo.........
................
................
................
................
""")

        a("leaf", """
................
................
......oo........
....oowaao......
...owaaaaao.....
..owaaaaaaaao...
..oaaaaaaaaao...
..oaaawaaaao....
...oaaaaaao.....
....oaaao.......
......oao.......
......oao.......
.......o........
................
................
................
""")

        a("bubble", """
................
................
......oooo......
.....o...o......
....o.w...o.....
....o..w..o.....
...o.......o....
...o.......o....
....o.....o.....
.....o...o......
......oooo......
................
................
................
................
................
""")

        a("bolt", """
................
................
........ooo.....
.......owao.....
......owao......
.....owaao......
....owaao.......
...owaoooooo....
..owwaawwwwao...
....oo....oao...
..........oao...
...........oo...
................
................
................
................
""")

        a("shard", """
................
................
......o.........
.....owao.......
.....owaao......
....owaaaao.....
....owaaao......
...owaaao.......
...owaaao.......
....owaao.......
....owao........
.....oo.........
................
................
................
................
""")

        a("portal", """
................
................
.....oooooo.....
...ooaaaaaaoo...
..oaaAAAAAAaao..
..oaAaaaaaaAao..
..oaAaggaagAao..
..oaAagwwgagAo..
..oaAaggaagAao..
..oaAaaaaaaAao..
..oaaAAAAAAaao..
...ooaaaaaaoo...
.....oooooo.....
................
................
................
""")

        a("gravel", """
................
................
................
...oo...o.o.....
..oaao.owaoo....
.oaaaooaaaao.o..
.oaaaowaaoowaao.
.oaaaaaaaaoaaao.
..oaaoaaaaaaao..
.oaaaaoaaaoaaao.
.oaaowaaaaaaao..
.oaaaaaaoaaao...
..ooaaoooaoo....
................
................
................
""")
    }

    /** Common palettes. */
    val OUTLINE = 0xFF14151C.toInt()
    val WHITE = 0xFFFFFFFF.toInt()
    val GLOW = 0xFFFFF3A8.toInt()

    fun pal(vararg defs: Pair<Char, Int>): MutableMap<Char, Int> {
        val m = HashMap<Char, Int>()
        m['o'] = OUTLINE; m['w'] = WHITE; m['g'] = GLOW
        for ((c, v) in defs) m[c] = v.toInt()
        return m
    }
}
