"use client";
import { useEffect,useMemo,useState } from "react";
import { Bot,BrainCircuit,CheckCircle2,ChevronRight,Code2,Folder,GitBranch,Play,Plus,Search,Settings,ShieldCheck,Sparkles,Terminal,XCircle,Zap,Save,RefreshCw } from "lucide-react";
import styles from "./page.module.css";
type Event={id:string;at:string;kind:string;message:string;role?:string;detail?:string};
type Provider={id:string;model:string;configured:boolean};
const starter="Build a production-ready full-stack SaaS application with authentication, PostgreSQL data model, REST API, responsive dashboard, tests, Docker support and deployment configuration.";
export default function Home(){
 const [request,setRequest]=useState("");const [events,setEvents]=useState<Event[]>([]);const [running,setRunning]=useState(false);const [projectId,setProjectId]=useState<string|null>(null);const [files,setFiles]=useState<string[]>([]);const [active,setActive]=useState("README.md");const [content,setContent]=useState("");const [dirty,setDirty]=useState(false);const [tab,setTab]=useState<"code"|"diff"|"chat">("code");const [settings,setSettings]=useState(false);const [apiKey,setApiKey]=useState("");const [provider,setProvider]=useState("mistral");const [providers,setProviders]=useState<Provider[]>([]);
 useEffect(()=>{setRequest(starter);fetch("/api/providers").then(r=>r.json()).then(setProviders).catch(()=>{});setApiKey(localStorage.getItem("forgeai_api_key")||"");setProvider(localStorage.getItem("forgeai_provider")||"mistral")},[]);
 async function refreshFiles(id:string){const r=await fetch(`/api/projects/${id}/files`);if(r.ok){const d=await r.json();setFiles(d.files||[]);if((d.files||[]).includes(active))loadFile(id,active)}}
 async function loadFile(id:string,path:string){const r=await fetch(`/api/projects/${id}/files?path=${encodeURIComponent(path)}`);if(r.ok){const d=await r.json();setContent(d.content||"");setDirty(false)}}
 async function saveFile(){if(!projectId||!dirty)return;const r=await fetch(`/api/projects/${projectId}/files`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({path:active,content})});if(r.ok){setDirty(false);refreshFiles(projectId);setEvents(v=>[...v,{id:crypto.randomUUID(),at:new Date().toISOString(),kind:"success",message:`Saved ${active}`,role:"coder"}])}}
 async function build(){
  if(!request.trim()||running)return;setRunning(true);setEvents([]);setFiles([]);setContent("");setDirty(false);
  try{
   const res=await fetch("/api/agent",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({request,provider,apiKey:apiKey||undefined})});
   if(!res.ok){const d=await res.json().catch(()=>({}));throw new Error(d.error||`HTTP ${res.status}`)}
   if(!res.body)throw new Error("Streaming response unavailable");
   const reader=res.body.getReader(),dec=new TextDecoder();let buf="";
   while(true){
    const {value,done}=await reader.read();if(done)break;buf+=dec.decode(value,{stream:true});const chunks=buf.split("\n\n");buf=chunks.pop()||"";
    for(const c of chunks){
     const line=c.split("\n").find(x=>x.startsWith("data: "));if(!line)continue;const d=JSON.parse(line.slice(6));
     if(d.type==="project"){setProjectId(d.project.id);setFiles(d.project.files||[])}
     if(d.type==="event")setEvents(v=>[...v,d.event]);
     if(d.type==="complete"){setProjectId(d.project.id);setFiles(d.project.files||[])}
     if(d.type==="error")setEvents(v=>[...v,{id:crypto.randomUUID(),at:new Date().toISOString(),kind:"error",message:"Agent failed",detail:d.error}]);
    }
   }
  }catch(e){setEvents(v=>[...v,{id:crypto.randomUUID(),at:new Date().toISOString(),kind:"error",message:"Request failed",detail:String(e)}])}
  finally{setRunning(false)}
 }
 const status=running?"ENGINEERING":projectId?"READY":"IDLE";const visibleFiles=files.length?files:["README.md","app/","lib/","tests/","Dockerfile"];
 return <main className={styles.shell}><header className={styles.top}><div className={styles.brand}><div className={styles.logo}><Sparkles size={18}/></div><b>ForgeAI</b><span className={styles.badge}>AUTONOMOUS SOFTWARE ENGINEER</span></div><div className={styles.topRight}><span className={styles.live}><span/> {status}</span><button className={styles.ghost}><GitBranch size={15}/> main</button><button className={styles.ghost} onClick={()=>setSettings(true)}><Settings size={15}/> Settings</button></div></header>
 <section className={styles.workspace}><aside className={styles.left}><div className={styles.sideTitle}><span>PROJECT</span><Plus size={14}/></div><div className={styles.projectCard}><Code2 size={16}/><div><b>{projectId?"ForgeAI Project":"New Software"}</b><small>{projectId?projectId.slice(0,12):"unsaved workspace"}</small></div></div><div className={styles.sideTitle}><span>FILES · {files.length}</span><Search size={14}/></div><div className={styles.files}>{visibleFiles.map(f=><button key={f} onClick={()=>{setActive(f);if(projectId&&!f.endsWith("/"))loadFile(projectId,f)}} className={active===f?styles.fileActive:styles.file}><span>{f.endsWith("/")?<Folder size={14}/>:<Code2 size={14}/>}</span>{f}</button>)}</div><div className={styles.leftBottom}><div><ShieldCheck size={15}/> Sandboxed execution</div><small>Commands require a worker; never run on production.</small></div></aside>
 <section className={styles.center}><div className={styles.tabs}><button className={tab==="code"?styles.tabActive:styles.tab} onClick={()=>setTab("code")}><Code2 size={15}/> Code</button><button className={tab==="diff"?styles.tabActive:styles.tab} onClick={()=>setTab("diff")}>⌘ Diff</button><button className={tab==="chat"?styles.tabActive:styles.tab} onClick={()=>setTab("chat")}><Bot size={15}/> Agent Chat</button><div className={styles.path}>{active}{dirty&&" • unsaved"}<button className={styles.save} onClick={saveFile} disabled={!dirty}><Save size={14}/> Save</button></div></div>
 {tab==="code"&&<div className={styles.editor}><div className={styles.lineNums}>{Array.from({length:Math.max(28,content.split("\n").length)},(_,i)=><span key={i}>{String(i+1).padStart(3,"0")}</span>)}</div><textarea spellCheck={false} value={content} placeholder="Select a generated file to edit it." onChange={e=>{setContent(e.target.value);setDirty(true)}}/></div>}
 {tab==="diff"&&<div className={styles.empty}><Zap size={30}/><h3>Change control</h3><p>Every file mutation is streamed into the activity log. The editor lets you review and save changes.</p></div>}
 {tab==="chat"&&<div className={styles.chat}>{events.length?events.map(e=><div key={e.id} className={styles.chatItem}><b>{e.role||"agent"}</b><span>{e.message}</span>{e.detail&&<small>{e.detail.slice(0,1000)}</small>}</div>):<div className={styles.empty}>No agent messages yet.</div>}</div>}
 <div className={styles.prompt}><textarea value={request} onChange={e=>setRequest(e.target.value)} placeholder="Describe what you want to build. ForgeAI will plan, code, test, debug and verify it."/><div className={styles.promptBar}><div className={styles.chips}><span><BrainCircuit size={13}/> Planner</span><span><Terminal size={13}/> Tools</span><span><ShieldCheck size={13}/> Verify</span><span>{provider}</span></div><button className={styles.run} disabled={running} onClick={build}>{running?<><span className={styles.spinner}/> Engineering...</>:<><Play size={15}/> Build Software</>}</button></div></div></section>
 <aside className={styles.right}><div className={styles.panelHead}><span>AGENT CONTROL</span><span className={styles.dot}/></div><div className={styles.pipeline}>{["Understand","Architecture","Implement","Build & Test","Debug","Verify","Review"].map((x,i)=><div key={x} className={styles.step}><div className={styles.stepIcon}>{running&&i===2?<RefreshCw size={13}/>:i<2&&!running?<CheckCircle2 size={14}/>:<span>{i+1}</span>}</div><div><b>{x}</b><small>{running&&i===2?"working":i<2?"ready":"queued"}</small></div>{i<6&&<ChevronRight size={13}/>}</div>)}</div><div className={styles.panelHead}>LIVE ACTIVITY</div><div className={styles.activity}>{events.length===0?<div className={styles.emptySmall}><Bot size={22}/><span>Agent activity will stream here.</span></div>:events.slice(-20).reverse().map(e=><div className={styles.activityItem} key={e.id}><div className={styles.activityIcon}>{e.kind==="error"?<XCircle size={13}/>:e.kind==="success"?<CheckCircle2 size={13}/>:<Zap size={13}/>}</div><div><b>{e.message}</b>{e.detail&&<small>{e.detail.slice(0,180)}</small>}<time>{new Date(e.at).toLocaleTimeString()}</time></div></div>)}</div></aside></section>
 {settings&&<div className={styles.modalBackdrop} onMouseDown={()=>setSettings(false)}><div className={styles.modal} onMouseDown={e=>e.stopPropagation()}><div className={styles.modalHead}><div><b>ForgeAI Settings</b><small>Configure a model for this browser session.</small></div><button onClick={()=>setSettings(false)}>×</button></div><label>Provider<select value={provider} onChange={e=>{setProvider(e.target.value);localStorage.setItem("forgeai_provider",e.target.value)}}>{providers.map(p=><option key={p.id} value={p.id}>{p.id} · {p.model}{p.configured?" · server key":""}</option>)}</select></label><label>API key<input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Paste provider key (not committed to Git)"/></label><p className={styles.warn}>Browser-entered keys are sent only with agent requests and stored locally in this browser. For production, prefer server-side environment variables.</p><button className={styles.saveSettings} onClick={()=>{localStorage.setItem("forgeai_api_key",apiKey);setSettings(false)}}>Save settings</button></div></div>}
 </main>
}
