import crypto from "node:crypto";
import { createWorkspace,listFiles,readFileSafe,writeFileSafe,deleteFileSafe } from "./workspace";
import { saveState,loadState } from "./store";
import { getProvider,parseActions } from "./providers";
import { runCommand } from "./runner";
import { AgentEvent,ProjectState,Task,ModelAction,AgentRole } from "./types";
const id=()=>crypto.randomUUID(); const now=()=>new Date().toISOString();
function push(s:ProjectState,kind:AgentEvent["kind"],message:string,role?:AgentRole,detail?:string){const e={id:id(),at:now(),kind,message,role,detail};s.events.push(e);s.updatedAt=e.at;return e;}
function tasks():Task[]{return [["Understand request","planner"],["Architecture","architect"],["Implement","coder"],["Build & test","tester"],["Debug & verify","debugger"],["Review","reviewer"]].map(([title,role],i)=>({id:id(),title,description:title,role:role as AgentRole,status:"pending",priority:i+1,dependsOn:[],retries:0,maxRetries:3}));}
export async function createProject(request:string,name="ForgeAI Project"){const pid=id(),root=await createWorkspace(pid);const s:ProjectState={id:pid,name,root,request,stack:[],tasks:tasks(),events:[],files:[],memory:[],iteration:0,status:"running",createdAt:now(),updatedAt:now()};push(s,"info","Isolated workspace created","planner");await saveState(s);return s;}
const SYSTEM=`You are ForgeAI, a senior autonomous software engineering agent. You must actually engineer software, not just explain it. Work in a bounded workspace. Return ONLY JSON with an actions array. Actions: write_file {path,content}; read_file {path}; delete_file {path}; run_command {command}; note {message}; finish {message}. Never use absolute paths or shell operators. Inspect relevant files before editing. Choose the best stack for the request. Keep changes incremental. After implementation, run available build/type/test commands. If execution is unavailable, still complete code and clearly report that verification is blocked. Never claim a build passed unless a command result proves it.`;
export async function runAgent(s:ProjectState,emit:(e:AgentEvent)=>Promise<void>,opts:{apiKey?:string;provider?:string;model?:string}={}){const provider=getProvider(opts.provider,opts.apiKey,opts.model);if(!provider){const e=push(s,"error","No AI provider configured","planner","Add an API key in Settings or configure a server environment key.");s.status="failed";await saveState(s);await emit(e);return s;}await emit(push(s,"info",`Connected to ${provider.name} · ${provider.model}`,"planner"));const max=Math.max(1,Math.min(20,Number(process.env.FORGEAI_MAX_ITERATIONS||12)));for(let i=1;i<=max;i++){s.iteration=i;const files=await listFiles(s.root);s.files=files;const previews:string[]=[];for(const f of files.slice(0,60)){try{const c=await readFileSafe(s.root,f);previews.push(`--- ${f} ---\n${c.slice(0,3500)}`)}catch{}}const prompt=`REQUEST:\n${s.request}\n\nITERATION ${i}/${max}\nFILES:\n${files.join("\n")||"(empty)"}\n\nRELEVANT CONTENT:\n${previews.join("\n").slice(0,30000)}\n\nMEMORY:\n${s.memory.slice(-20).join("\n")}\n\nRECENT EVENTS:\n${s.events.slice(-10).map(x=>`${x.kind}: ${x.message} ${x.detail||""}`).join("\n")}`;let raw="";try{raw=await provider.complete(SYSTEM,prompt,opts.apiKey)}catch(e){const ev=push(s,"error","AI request failed","planner",String(e));await saveState(s);await emit(ev);if(i===max)s.status="failed";continue}const actions=parseActions(raw);if(!actions.length){const ev=push(s,"warning","Model returned no executable actions","debugger",raw.slice(0,1200));await emit(ev);continue}for(const a of actions.slice(0,10) as ModelAction[]){try{if(a.type==="write_file"&&a.path&&a.content!==undefined){await writeFileSafe(s.root,a.path,a.content);await emit(push(s,"tool",`Wrote ${a.path}`,"coder"))}else if(a.type==="read_file"&&a.path){const c=await readFileSafe(s.root,a.path);await emit(push(s,"tool",`Read ${a.path}`,"coder",c.slice(0,1800)))}else if(a.type==="delete_file"&&a.path){await deleteFileSafe(s.root,a.path);await emit(push(s,"tool",`Deleted ${a.path}`,"coder"))}else if(a.type==="run_command"&&a.command){const r=await runCommand(s.root,a.command);await emit(push(s,r.code===0?"command":"error",`${a.command} → ${r.code}`,"tester",(r.stdout+"\n"+r.stderr).slice(0,3000)))}else if(a.type==="note"&&a.message){s.memory.push(a.message);await emit(push(s,"info",a.message,"reviewer"))}else if(a.type==="finish"){s.status="done";await emit(push(s,"success",a.message||"Engineering complete","reviewer"));await saveState(s);return s}}catch(e){await emit(push(s,"error",`Action failed: ${a.type}`,"debugger",String(e)))}}await saveState(s)}if(s.status==="running"){s.status="failed";await emit(push(s,"error","Iteration limit reached","debugger"));await saveState(s)}return s}
export async function getProject(id:string){return loadState(id)}
